AWSTemplateFormatVersion: "2010-09-09"
Description: "Erstellt eine EC2-Instanz mit SSH-Zugriff"

Parameters:
  SshKey:
    Description: "Name des SSH-Schlüsselpaars für den Zugriff auf die EC2-Instanz"
    Type: String
    Default: "my-key-pair" # Ersetze dies durch deinen tatsächlichen SSH-Schlüssel-Namen

  SubnetId:
    Description: "Subnetz-ID für die EC2-Instanz"
    Type: AWS::EC2::Subnet::Id

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref SshKey
      SubnetId: !Ref SubnetId
      ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2 (x86_64) - Region eu-central-1

Outputs:
  InstanceId:
    Description: "Die ID der EC2-Instanz"
    Value: !Ref MyEC2Instance


